### ISSUE TITLE
Bot unavailable while calculating huge expressions

### ISSUE THREAD

**Issue by ntoneee** [format37/calcubot_python#1]
How to reproduce:
- Ask bot to calculate something like: `@Calcubot 1234**4567**78910**101112` (some big number in result)
- Try to do `@Calcubot 35+46` (simple expression)

The bot won't respond, possibly because he is still calculating `1234**4567**...`

**Comment by format37** [comment]
> How to reproduce:
> 
> * Ask bot to calculate something like: `@Calcubot 1234**4567**78910**101112` (some big number in result)
> * Try to do `@Calcubot 35+46` (simple expression)
> 
> The bot won't respond, possibly because he is still calculating `1234**4567**...`

Great! Thanx! I added '**' to declined words, to fix this security hole.

**Comment by format37** [comment]
> How to reproduce:
> 
> * Ask bot to calculate something like: `@Calcubot 1234**4567**78910**101112` (some big number in result)
> * Try to do `@Calcubot 35+46` (simple expression)
> 
> The bot won't respond, possibly because he is still calculating `1234**4567**...`

Found and made better solution, with subprocess and resource.setrlimit(resource.RLIMIT_CPU, (1, 1))
now any ** is available and limited by execution time == 1s
